GET http://localhost:8888/api/vocabulary/enrich?english=tree&german=Baum

GET http://localhost:8888/api/imap/enabled

GET http://localhost:8888/api/imap/folders

GET http://localhost:8888/api/imap/folder/INBOX

GET http://localhost:8888/api/imap/message/INBOX/1018

POST http://localhost:8888/api/imap/mark

{
    "messageId": 60,
    "folder": "Entwürfe",
    "seen": false
}

POST http://localhost:8888/api/imap/move

{
    "messageId": 121,
    "sourceFolder": "Archiv",
    "targetFolder": "INBOX"
}

POST http://localhost:8888/api/imap/purge

{
    "folder": "Papierkorb"
}

POST http://localhost:8888/api/imap/draft

{
    "id": 67,
    "subject": "Draft Subject2",
    "from": {
        "name": "Sender Name2",
        "email": "sender2@example.com"
    },
    "to": [
        {
            "name": "Recipient Name",
            "email": "recipient@example.com"
        },
        {
            "email": "recipient2@example.com"
        }
    ],
    "date": "2024-10-01T12:00:00Z",
    "bodyText": "This is a draft body.2",
    "attachments": [
        {
            "name": "attachment.txt",
            "size": 1024,
            "type": "text/plain",
            "content": "SGVsbG8gd29ybGQh"
        }
    ]
}

DELETE http://localhost:8888/api/imap/draft/64

GET http://localhost:8888/api/imap/attachment/INBOX/1023/Signatur_KLEIN.jpg

GET http://localhost:8888/api/imap/contacts

POST http://localhost:8888/api/imap/send

{
    "id": 67,
    "subject": "Draft Subject23",
    "to": [
        {
            "name": "Tobi",
            "email": "tobias.zeising@aditu.de"
        }
    ],
    "cc": [
        {
            "name": "Recipient Name",
            "email": "info@lesestunden.de"
        }
    ],
    "date": "2025-09-25T12:00:00Z",
    "bodyText": "This is example body text.",
    "attachments": [
        {
            "name": "attachment.txt",
            "size": 1024,
            "type": "text/plain",
            "content": "SGVsbG8gd29ybGQh"
        }
    ]
}

GET http://localhost:8888/api/news/update

GET http://localhost:8888/api/images?q=tree