version: '3.6'

services:
  php:
    container_name: php-markdown
    build: ./
    ports:
        - 8888:80
    volumes:
        - ./../:/var/www/html
        - ./logs/apache2:/var/log/apache2
        - ./logs/php:/var/log/php